name: build dev image

on:
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: tcp://forgejo-docker-in-docker-1:2375
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker-build/
          file: ./docker-build/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          cleanup: true
          tags: |
            ${{ secrets.DOCKER_USER }}/docker-owndyndns-netcup:dev
