name: Build and push dyndns-netcup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    -
      name: Set up variables
      run: |
        VER=$(cat ./docker-build/VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./docker-build
        file: ./docker-build/Dockerfile
        platforms: |
          linux/arm/v7
          linux/arm64
          linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_USER }}/docker-owndyndns-netcup:${{ env.VERSION }}
          ${{ secrets.DOCKER_USER }}/docker-owndyndns-netcup:latest
